stages:
  - publish # Deploy new version of package to registry

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest

variables:
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip # Set folder in working dir for cache

version_and_publish:
  stage: publish
  image: python:latest
  variables:
    GIT_DEPTH: 0
    GIT_COMMIT_AUTHOR: "semantic-release <$GITLAB_USER_EMAIL>"
  before_script:
    - pip install .
  script:
    - git checkout "$CI_COMMIT_REF_NAME"
    - semantic-release version
  cache:
    paths:
      - ${PIP_CACHE_DIR}
  rules:
    # Don't run on automatic commits
    - if: $CI_COMMIT_AUTHOR =~ /semantic-release.*/
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always

