stages:
  - release

release:
  stage: release
  image: node:18
  only:
    - main
  variables:
    # These variables should be set in GitLab’s CI/CD settings as protected secrets.
    GITLAB_TOKEN: $GITLAB_TOKEN
    # PYPI_TOKEN: $PYPI_TOKEN
  before_script:
    # Install Python 3.11 (adjust as needed for your base image)
    - apt-get update && apt-get install -y python3.11
  script:
    # Install dependencies (including semantic-release)
    - npm install
    # Run semantic-release
    - npx semantic-release
