repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.4.1
    hooks:
    - id: commitizen                  # Checks commit messages
      stages: [commit-msg]
    - id: commitizen-branch           # Checks branch commit messages
      stages: [pre-push]
